<?php

/**
 * @link https://alexandr-zr.ru/
 * @author Alexandr Drachenin <alexdrachenin98@gmail.com>
 * @copyright Copyright (c) 2020-2026 ZR studio (https://alexandr-zr.ru/)
 */

$moduleId = 'zr.paidaccess';

\Bitrix\Main\Loader::registerAutoLoadClasses($moduleId, [
    'Zr\PaidAccess\PaidAccessCore' => 'classes/general/PaidAccessCore.php',
    'Zr\PaidAccess\Access\AccessBlockHandler' => 'lib/access/AccessBlockHandler.php',
    'Zr\PaidAccess\Access\RegistrationPaymentHandler' => 'lib/access/RegistrationPaymentHandler.php',
    'Zr\PaidAccess\Access\AccessControl' => 'lib/access/AccessControl.php',
    'Zr\PaidAccess\Access\AccessTemplate' => 'lib/access/AccessTemplate.php',
    'Zr\PaidAccess\Options\ModuleOptionsProvider' => 'lib/options/ModuleOptionsProvider.php',
    'Zr\PaidAccess\Options\ModuleOptionsStructure' => 'lib/options/ModuleOptionsStructure.php',
    'Zr\PaidAccess\Payment\PaymentRepository' => 'lib/payment/PaymentRepository.php',
    'Zr\PaidAccess\Payment\GatewayTransactionRepository' => 'lib/payment/GatewayTransactionRepository.php',
    'Zr\PaidAccess\Payment\SubscriptionPaymentService' => 'lib/payment/SubscriptionPaymentService.php',
    'Zr\PaidAccess\Payment\PayBlockPageRenderer' => 'lib/payment/PayBlockPageRenderer.php',
    'Zr\PaidAccess\Payment\PaymentPageErrorRenderer' => 'lib/payment/PaymentPageErrorRenderer.php',
    'Zr\PaidAccess\Payment\PaymentCompletionService' => 'lib/payment/PaymentCompletionService.php',
    'Zr\PaidAccess\Payment\PaymentWebhookService' => 'lib/payment/PaymentWebhookService.php',
    'Zr\PaidAccess\Payment\PaymentWebhookStatusService' => 'lib/payment/PaymentWebhookStatusService.php',
    'Zr\PaidAccess\Payment\PaymentCancellationService' => 'lib/payment/PaymentCancellationService.php',
    'Zr\PaidAccess\Gateway\GatewayFactory' => 'lib/Gateway/GatewayFactory.php',
    'Zr\PaidAccess\Gateway\GatewayRepository' => 'lib/Gateway/GatewayRepository.php',
    'Zr\PaidAccess\Gateway\Provider\GatewayProviderRegistry' => 'lib/Gateway/Provider/GatewayProviderRegistry.php',
    'Zr\PaidAccess\Gateway\Provider\GatewayProviderLoader' => 'lib/Gateway/Provider/GatewayProviderLoader.php',
    'Zr\PaidAccess\Gateway\Provider\AbstractGatewayProvider' => 'lib/Gateway/Provider/AbstractGatewayProvider.php',
    'Zr\PaidAccess\Gateway\Contract\GatewayProviderInterface' => 'lib/Gateway/Contract/GatewayProviderInterface.php',
    'Zr\PaidAccess\Admin\AdminJsonResponse' => 'lib/Admin/AdminJsonResponse.php',
    'Zr\PaidAccess\Admin\GatewayFormBuilder' => 'lib/Admin/GatewayFormBuilder.php',
    'Zr\PaidAccess\Admin\PaymentAdminService' => 'lib/Admin/PaymentAdminService.php',
    'Zr\PaidAccess\Admin\SubscriberAdminService' => 'lib/Admin/SubscriberAdminService.php',
    'Zr\PaidAccess\Admin\StatusBadgeRenderer' => 'lib/Admin/StatusBadgeRenderer.php',
    'Zr\PaidAccess\Gateway\Contract\PaymentGatewayInterface' => 'lib/Gateway/Contract/PaymentGatewayInterface.php',
    'Zr\PaidAccess\Gateway\Dto\InitPaymentRequest' => 'lib/Gateway/Dto/InitPaymentRequest.php',
    'Zr\PaidAccess\Gateway\Dto\InitPaymentResult' => 'lib/Gateway/Dto/InitPaymentResult.php',
    'Zr\PaidAccess\Gateway\Dto\WebhookHandleResult' => 'lib/Gateway/Dto/WebhookHandleResult.php',
    'Zr\PaidAccess\Subscription\SubscriptionService' => 'lib/subscription/SubscriptionService.php',
    'Zr\PaidAccess\Subscription\BillingPolicy' => 'lib/subscription/BillingPolicy.php',
    'Zr\PaidAccess\Subscription\SubscriptionAmountBreakdown' => 'lib/subscription/SubscriptionAmountBreakdown.php',
    'Zr\PaidAccess\Subscription\BillingDebtService' => 'lib/subscription/BillingDebtService.php',
    'Zr\PaidAccess\Subscription\BillingDebtAgent' => 'lib/subscription/BillingDebtAgent.php',
    'Zr\PaidAccess\Subscription\SubscriptionReminderService' => 'lib/subscription/SubscriptionReminderService.php',
    'Zr\PaidAccess\Subscription\SubscriptionReminderAgent' => 'lib/subscription/SubscriptionReminderAgent.php',
    'Zr\PaidAccess\Notification\SubscriptionNotificationService' => 'lib/notification/SubscriptionNotificationService.php',
    'Zr\PaidAccess\Notification\NotificationLogRepository' => 'lib/notification/NotificationLogRepository.php',
    'Zr\PaidAccess\Log\ModuleEventLogService' => 'lib/log/ModuleEventLogService.php',
    'Zr\PaidAccess\Log\AuditLogService' => 'lib/log/AuditLogService.php',
    'Zr\PaidAccess\Admin\EventLogAdminService' => 'lib/Admin/EventLogAdminService.php',
    'Zr\PaidAccess\Admin\LogCleanupAdminService' => 'lib/Admin/LogCleanupAdminService.php',
    'Zr\PaidAccess\Admin\GatewayTransactionAdminService' => 'lib/Admin/GatewayTransactionAdminService.php',
    'Zr\PaidAccess\Admin\GatewayTransactionContextRenderer' => 'lib/Admin/GatewayTransactionContextRenderer.php',
    'Zr\PaidAccess\Install\GatewayTransactionInstaller' => 'lib/install/GatewayTransactionInstaller.php',
    'Zr\PaidAccess\Admin\AdminEntityLinkRenderer' => 'lib/Admin/AdminEntityLinkRenderer.php',
    'Zr\PaidAccess\Admin\AuditContextRenderer' => 'lib/Admin/AuditContextRenderer.php',
    'Zr\PaidAccess\Admin\EventLogContextRenderer' => 'lib/Admin/EventLogContextRenderer.php',
    'Zr\PaidAccess\Admin\GatewayImportExportService' => 'lib/Admin/GatewayImportExportService.php',
    'Zr\PaidAccess\Enum\ModuleLogLevel' => 'lib/enum/ModuleLogLevel.php',
    'Zr\PaidAccess\Enum\NotificationType' => 'lib/enum/NotificationType.php',
    'Zr\PaidAccess\Tables\EventLogTable' => 'lib/tables/EventLogTable.php',
    'Zr\PaidAccess\Tables\AuditLogTable' => 'lib/tables/AuditLogTable.php',
    'Zr\PaidAccess\Tables\NotificationLogTable' => 'lib/tables/NotificationLogTable.php',
    'Zr\PaidAccess\Install\LogInstaller' => 'lib/install/LogInstaller.php',
    'Zr\PaidAccess\Payment\RegistrationPaymentService' => 'lib/payment/RegistrationPaymentService.php',
    'Zr\PaidAccess\Tools\Logger' => 'lib/tools/Logger.php',
    'Zr\PaidAccess\Tools\RequestContext' => 'lib/tools/RequestContext.php',
    'Zr\PaidAccess\Install\AgentInstaller' => 'lib/install/AgentInstaller.php',
    'Zr\PaidAccess\Install\PaymentInstaller' => 'lib/install/PaymentInstaller.php',
    'Zr\PaidAccess\Install\EventInstaller' => 'lib/install/EventInstaller.php',
    'Zr\PaidAccess\Notification\ReceiptNotificationService' => 'lib/notification/ReceiptNotificationService.php',
    'Zr\PaidAccess\Gateway\ReceiptDeliveryResolver' => 'lib/Gateway/ReceiptDeliveryResolver.php',
    'Zr\PaidAccess\Gateway\Dto\ReceiptDeliveryInfo' => 'lib/Gateway/Dto/ReceiptDeliveryInfo.php',
    'Zr\PaidAccess\Gateway\Contract\GatewayReceiptCapableInterface' => 'lib/Gateway/Contract/GatewayReceiptCapableInterface.php',
    'Zr\PaidAccess\Install\MailInstaller' => 'lib/install/MailInstaller.php',
    'Zr\PaidAccess\Install\GatewayInstaller' => 'lib/install/GatewayInstaller.php',
    'Zr\PaidAccess\Install\ComponentInstaller' => 'lib/install/ComponentInstaller.php',
    'Zr\PaidAccess\PublicUi\AccessStatusPresenter' => 'lib/Public/AccessStatusPresenter.php',
    'Zr\PaidAccess\PublicUi\PersonalSubscriptionViewService' => 'lib/Public/PersonalSubscriptionViewService.php',
    'Zr\PaidAccess\PublicUi\MemberListService' => 'lib/Public/MemberListService.php',
    'Zr\PaidAccess\PublicUi\FundWalletService' => 'lib/Public/FundWalletService.php',
    'Zr\PaidAccess\PublicUi\FundContributorService' => 'lib/Public/FundContributorService.php',
    'Zr\PaidAccess\Gateway\GatewayTestService' => 'lib/Gateway/GatewayTestService.php',
    'Zr\PaidAccess\Enum\PaymentStatus' => 'lib/enum/PaymentStatus.php',
    'Zr\PaidAccess\Enum\SubscriptionStatus' => 'lib/enum/SubscriptionStatus.php',
    'Zr\PaidAccess\Enum\GatewayEventType' => 'lib/enum/GatewayEventType.php',
    'Zr\PaidAccess\Enum\FundMovementType' => 'lib/enum/FundMovementType.php',
    'Zr\PaidAccess\Enum\FundMovementSource' => 'lib/enum/FundMovementSource.php',
    'Zr\PaidAccess\Fund\Exception\InsufficientFundBalanceException' => 'lib/Fund/Exception/InsufficientFundBalanceException.php',
    'Zr\PaidAccess\Fund\FundRepository' => 'lib/Fund/FundRepository.php',
    'Zr\PaidAccess\Fund\FundMovementRepository' => 'lib/Fund/FundMovementRepository.php',
    'Zr\PaidAccess\Fund\FundBalanceService' => 'lib/Fund/FundBalanceService.php',
    'Zr\PaidAccess\Fund\FundPaymentSiteResolver' => 'lib/Fund/FundPaymentSiteResolver.php',
    'Zr\PaidAccess\Fund\FundService' => 'lib/Fund/FundService.php',
    'Zr\PaidAccess\Fund\FundMovementService' => 'lib/Fund/FundMovementService.php',
    'Zr\PaidAccess\Admin\FundAdminService' => 'lib/Admin/FundAdminService.php',
    'Zr\PaidAccess\Install\FundInstaller' => 'lib/install/FundInstaller.php',
    'Zr\PaidAccess\Tables\GatewayTable' => 'lib/tables/GatewayTable.php',
    'Zr\PaidAccess\Tables\PaymentTable' => 'lib/tables/PaymentTable.php',
    'Zr\PaidAccess\Tables\GatewayTransactionTable' => 'lib/tables/GatewayTransactionTable.php',
    'Zr\PaidAccess\Tables\SubscriptionTable' => 'lib/tables/SubscriptionTable.php',
    'Zr\PaidAccess\Tables\FundTable' => 'lib/tables/FundTable.php',
    'Zr\PaidAccess\Tables\FundMovementTable' => 'lib/tables/FundMovementTable.php',
    'Zr\PaidAccess\Tables\TableInstaller' => 'lib/tables/TableInstaller.php',
]);

\Zr\PaidAccess\Gateway\Provider\GatewayProviderLoader::registerAutoload($moduleId);
